### ISSUE TITLE
sd_file_write.v中的模块找不到

### ISSUE THREAD

**Issue by DanielHCY** [InertialSensingAndAdvancedNavigationLab/FPGA-SDCardReaderAndWriter#2]
请问sd_file_write.v中的UpdateFatStartAddress模块在哪里，在工程中没有找到

**Comment by winyunq** [comment]
这2个模块位于src/FatUpdater.v中。这个仓库有国内gitee和国外github两个仓库，我之前推送到了gitee上，忘记推送到github上了。现已同步github仓库，你可以使用git pull命令更新获得src/FatUpdater.v文件

gitee仓库：https://gitee.com/winyunq/FPGA_SDCard/commit/79e3ed85bbabb837b73427bd9e87c86f7fe0cd6d

**Comment by DanielHCY** [comment]
> 这2个模块位于src/FatUpdater.v中。这个仓库有国内gitee和国外github两个仓库，我之前推送到了gitee上，忘记推送到github上了。现已同步github仓库，你可以使用git pull命令更新获得src/FatUpdater.v文件
> 
> gitee仓库：https://gitee.com/winyunq/FPGA_SDCard/commit/79e3ed85bbabb837b73427bd9e87c86f7fe0cd6d

好滴，感谢
